#input
n_input = int(input())
  
if n == 1 
    x11 = int(input()) 
    x11 = int(input()) 
if n==2
    x11 = int(input()) 
    x11 = int(input()) 
    x21 = int(input()) 
    x22 = int(input()) 
if n==3
    x11 = int(input()) 
    x11 = int(input()) 
    x21 = int(input()) 
    x22 = int(input()) 
    x31 = int(input()) 
    x32 = int(input())
if n == 4
    x11 = int(input()) 
    x11 = int(input()) 
    x21 = int(input()) 
    x22 = int(input()) 
    x31 = int(input()) 
    x32 = int(input())
    x41 = int(input()) 
    x42 = int(input()) 
if n ==5
    x11 = int(input()) 
    x11 = int(input()) 
    x21 = int(input()) 
    x22 = int(input()) 
    x31 = int(input()) 
    x32 = int(input())
    x41 = int(input()) 
    x42 = int(input())
    x51 = int(input()) 
    x52 = int(input())
if n == 6
    x11 = int(input()) 
    x11 = int(input()) 
    x21 = int(input()) 
    x22 = int(input()) 
    x31 = int(input()) 
    x32 = int(input())
    x41 = int(input()) 
    x42 = int(input())
    x51 = int(input()) 
    x52 = int(input())
    x61 = int(input())
    x62 = int(input())
if n == 7
    x11 = int(input()) 
    x11 = int(input()) 
    x21 = int(input()) 
    x22 = int(input()) 
    x31 = int(input()) 
    x32 = int(input())
    x41 = int(input()) 
    x42 = int(input())
    x51 = int(input()) 
    x52 = int(input())
    x61 = int(input())
    x62 = int(input())
    x71 = int(input())
    x72 = int(input())
if n == 8
    x11 = int(input()) 
    x11 = int(input()) 
    x21 = int(input()) 
    x22 = int(input()) 
    x31 = int(input()) 
    x32 = int(input())
    x41 = int(input()) 
    x42 = int(input())
    x51 = int(input()) 
    x52 = int(input())
    x61 = int(input())
    x62 = int(input())
    x71 = int(input())
    x72 = int(input())
    x81 = int(input())
    x82 = int(input())
if n == 9
    x11 = int(input()) 
    x11 = int(input()) 
    x21 = int(input()) 
    x22 = int(input()) 
    x31 = int(input()) 
    x32 = int(input())
    x41 = int(input()) 
    x42 = int(input())
    x51 = int(input()) 
    x52 = int(input())
    x61 = int(input())
    x62 = int(input())
    x71 = int(input())
    x72 = int(input())
    x81 = int(input())
    x82 = int(input())
    x91 = int(input())
    x92 = int(input())



